server: 
  port: 8080 
  
spring: 
  application: 
    name: apigateway 
  cloud: 
    gateway: 
      routes: 
        - id: itemservice 
          uri: http://itemservice:8081 
          predicates: 
            - Path=/items/** 
  
        - id: orderservice 
          uri: http://orderservice:8082 
          predicates: 
            - Path=/orders/** 
  
        - id: paymentservice 
          uri: http://paymentservice:8083 
          predicates: 
            - Path=/payments/** 

logging:
  level:
    org.springframework.cloud.gateway: DEBUG